# Site settings
title: TJBot Community Edition
description: Build your own DIY open source robot with AI services
baseurl: ""
url: "https://tjbot-ce.github.io"

# Build settings
markdown: kramdown
theme: minima

# Social links
github_username: tjbot-ce

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
