# Site settings
title: "TJBot: Community Edition"
description: "Open-source DIY robot integrated with AI services"
baseurl: ""
url: "https://tjbot-ce.github.io"

# Build settings
markdown: kramdown
theme: minima

# Social links
github_username: tjbot-ce

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - mise.toml
